ASP/Models/ErrorViewModel.cs
using System;

namespace test.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP/Controllers/FounderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using test.DataAccess;

namespace test.Controllers
{
    public class FounderController : Controller
    {
        readonly ApplicationContext db;
        public FounderController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Founders(int clientId)
        {
            IEnumerable<Founder> founders = db.Founders.Where(c => c.ClientId == clientId).ToList();
            ViewBag.ClientId = clientId;
            return View(founders);
        }

        public IActionResult AllFounders()
        {
            IEnumerable<Founder> founders = db.Founders;
            return View("Founders", founders);
        }

        public IActionResult AddFounder(int clientId)
        {
            return View(clientId);
        }

        [HttpPost]
        public IActionResult AddFounder(Founder founder)
        {
            founder.CreateDate = DateTime.Now;
            founder.UpdateDate = DateTime.Now;
            db.Founders.Add(founder);
            db.SaveChanges();
            return RedirectToAction("Founders", founder.ClientId);
        }

        public IActionResult EditFounder(int founderId)
        {
            var founder = db.Founders.Find(founderId);
            return View(founder);
        }

        [HttpPost]
        public IActionResult EditFounder(Founder founder)
        {
            founder.UpdateDate = DateTime.Now;
            db.Update(founder);
            db.SaveChanges();
            return RedirectToAction("Founders");
        }

        [HttpPost]
        public IActionResult DeleteFounder(int founderId)
        {
            var founder = db.Founders.Find(founderId);
            if (founder != null)
            {
                db.Founders.Remove(founder);
                db.SaveChanges();
            }
            return RedirectToAction("Founders");
        }
    }
}

ASP/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using test.DataAccess;

namespace test.Controllers
{

    public class HomeController : Controller
    {
        readonly ApplicationContext db;
        public HomeController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View(db.Clients);
        }

        [HttpGet]
        public IActionResult AddClient()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddClient(Client client)
        {
            if (!ModelState.IsValid)
                return Content($"{client.Name} - {client.INN}");

            client.CreateDate = client.UpdateDate = DateTime.Now;
            db.Clients.Add(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditClient(int clientId)
        {
            return View(db.Clients.Find(clientId));
        }

        [HttpPost]
        public IActionResult EditClient(Client client)
        {
            client.UpdateDate = DateTime.Now;
            db.Update(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteClient(int id)
        {
            var client = db.Clients.Find(id);
            if (client != null)
            {
                db.Clients.Remove(client);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ASP/Views/Founder/AddFounder.cshtml
@model int
@{
    ViewData["Title"] = "Добавление учредителя";
}

<div>
    <h3>Форма добавления учредителя</h3>
    <br />
    <form method="post" class="form-row">
        <div class="form-group">
            <input type="hidden"  id="ClientId" name="ClientId" value="@Model">
            <div class="form-group row">
                <label for="Surname">Фамилия</label>
                <input class="form-control" id="Surname" name="Surname" />
            </div>
            <div class="form-group row">
                <label for="Name">Имя</label>
                <input type="text" class="form-control" id="Name" name="Name" />
            </div>
            <div class="form-group row">
                <label for="Patronymic">Отчество</label>
                <input type="text" class="form-control" id="Patronymic" name="Patronymic" />
            </div>
            <div class="form-group row">
                <label for="INN">ИНН</label>
                <input type="text" class="form-control" id="INN" name="INN" />
            </div>
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-lg-5" role="group" aria-label="first group">
                    <input type="submit" class="btn btn-primary btn-lg" value="Сохранить" />
                </div>
                <div class="btn-group mr-lg-5" role="group" aria-label="second group">
                    <input class="btn btn-secondary btn-lg" type="button" onclick="window.location.replace('/')" value="Отмена" />
                </div>
            </div>
        </div>
    </form>
</div>

ASP/Views/Founder/EditFounder.cshtml
@model test.DataAccess.Founder
@{
    ViewData["Title"] = "Редактирование учредителя";
}

<h3>Учредитель</h3>
<br />
<form method="post" class="form-row">
    <input type="hidden" name="ClientId" value="@Model.ClientId">
    <input type="hidden" name="FounderId" value="@Model.FounderId">
    <input type="hidden" name="CreateDate" value="@Model.CreateDate">
    <div class="form-group">
        <div class="form-group row">
            <label for="Surname">Фамилия</label>
            <input type="text" class="form-control" id="Surname" name="Surname" value="@Model.Surname" />
        </div>
        <div class="form-group row">
            <label for="Name">Имя</label>
            <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name" />
        </div>
        <div class="form-group row">
            <label for="Patronymic">Отчество</label>
            <input type="text" class="form-control" id="Patronymic" name="Patronymic" value="@Model.Patronymic" />
        </div>
        <div class="form-group row">
            <label for="INN">ИНН</label>
            <input type="text" class="form-control" id="INN" name="INN" value="@Model.INN" />
        </div>
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-lg-5" role="group" aria-label="first group">
                <input type="submit" class="btn btn-primary btn-lg" value="Применить" />
            </div>
            <div class="btn-group mr-lg-5" role="group" aria-label="second group">
                <input class="btn btn-secondary btn-lg" type="button" onclick="window.location.replace('/')" value="Отмена" />
            </div>
        </div>
    </div>
</form>

ASP/Views/Founder/Founders.cshtml
@model IEnumerable<test.DataAccess.Founder>
@{
    ViewData["Title"] = "Учредители";
}

<h3>Список учредителей</h3>
<table class="table table-sm table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>ИНН</th>
            <th>Дата внесения в базу</th>
            <th>Дата редактирования</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    @foreach (var founder in Model)
    {
        <tr>
            <td>@founder.Surname</td>
            <td>@founder.Name</td>
            <td>@founder.Patronymic</td>
            <td>@founder.INN</td>
            <td>@founder.CreateDate</td>
            <td>@founder.UpdateDate</td>
            <td> <a asp-action="EditFounder" asp-route-FounderId="@founder.FounderId" class="btn btn-sm btn-primary"> <i class="fa fa-edit"></i> Редактировать</a></td>
            <td>
                @using (Html.BeginForm("DeleteFounder", "Founder", new { founderId = founder.FounderId }, FormMethod.Post))
                {
                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Удалить</button>
                }
            </td>
        </tr>
    }
</table>
<a asp-action="AddFounder" asp-route-clientId="@ViewBag.ClientId" >Добавить учредителя</a>
<a asp-action="Index" asp-controller="Home">Переход к организациям</a>

ASP/Views/Home/AddClient.cshtml
@model Client

@{
    ViewData["Title"] = "Добавление клиента";
}

<h3>Клиент</h3>
<form method="post" class="form-row" asp-action="AddClient">
        <div class="validation" asp-validation-summary="All"></div>
    <div class="form-group">
        <div class="form-group row">
            <label asp-for="Name">Имя</label>
            <input class="form-control" asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group row">
            <label asp-for="INN">ИНН</label>
            <input class="form-control" asp-for="INN" />
            <span asp-validation-for="INN"></span>
        </div>
        <div class="form-group row">
            <label asp-for="IsIndividual">Физлицо </label>
            @Html.CheckBox(nameof(test.DataAccess.Client.IsIndividual))
        </div>
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-lg-5" role="group" aria-label="first group">
                <input type="submit" class="btn btn-primary btn-lg" value="Применить" />
            </div>
            <div class="btn-group mr-lg-5" role="group" aria-label="second group">
                <input class="btn btn-secondary btn-lg" type="button" onclick="window.location.replace('/')" value="Отмена" />
            </div>
        </div>
    </div>
</form>

ASP/Views/Home/EditClient.cshtml
@model test.DataAccess.Client
@{
    ViewData["Title"] = "Редактирование клиента";
}

<h3>Клиент</h3>
<form method="post" class="form-row">
    <input type="hidden" name="ClientId" value="@Model.ClientId">
    <input type="hidden" name="CreateDate" value="@Model.CreateDate">
    <div class="form-group">
        <div class="form-group row">
            <label asp-for="Name">Имя</label>
            <input class="form-control" asp-for="Name" value="@Model.Name" />
            <span asp-validation-for="Name"></span>
        </div>
        <div class="form-group row">
            <label asp-for="INN">ИНН</label>
            <input class="form-control" asp-for="INN" value="@Model.INN" />
            <span asp-validation-for="INN"></span>
        </div>
        <div class="form-group row">
            <label asp-for="IsIndividual">Физлицо </label>
            <input type="checkbox" asp-for="IsIndividual" value="@Model.IsIndividual"/>
        </div>
        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-lg-5" role="group" aria-label="first group">
                <input type="submit" class="btn btn-primary btn-lg" value="Применить" />
            </div>
            <div class="btn-group mr-lg-5" role="group" aria-label="second group">
                <input class="btn btn-secondary btn-lg" type="button" onclick="window.location.replace('/')" value="Отмена" />
            </div>
        </div>
    </div>
</form>

ASP/Views/Home/Index.cshtml
@model IEnumerable<test.DataAccess.Client>
@{
    ViewData["Title"] = "Клиенты";
}

<h3>Список организаций</h3>
<table class="table table-sm table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>Наименование</th>
            <th>ИНН</th>
            <th>Физлицо</th>
            <th>Дата внесения в базу</th>
            <th>Дата редактирования</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    @foreach (var client in Model)
    {
        <tr>
            <td>@client.Name</td>
            <td>@client.INN</td>
            <td>@client.IsIndividual</td>
            <td>@client.CreateDate</td>
            <td>@client.UpdateDate</td>
            <td>
                <a href="@Url.RouteUrl(new { Controller = "Founder", Action = "Founders", clientId = @client.ClientId })" class="btn btn-sm btn-primary">
                    <i class="fa fa-address-card"></i>
                    Учредители
                </a>
            </td>
            <td>
                <a href="@Url.RouteUrl(new { Controller = "Home", Action = "EditClient", clientId = @client.ClientId })" class="btn btn-sm btn-primary">
                    <i class="fa fa-edit"></i>
                    Редактировать
                </a>
            </td>
            <td>
                @using (Html.BeginForm("DeleteClient", "Home", new { id = client.ClientId }, FormMethod.Post))
                {
                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Удалить</button>
                }

            </td>
        </tr>
    }
</table>
<a href="/home/addclient">Добавить новую организацию</a>

ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @await Html.PartialAsync("_ValidationScriptsPartial");
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm  navbar-toggleable-sm navbar-dark bg-primary mb-1">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i></a>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">На главную</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Founder" asp-action="AllFounders" >Список всех учредителей</a>
                        </li>
                    </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</body>
</html>